include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    todo: ignore
    sdk_version_async_exported_from_core: ignore
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore
  exclude:
    - "example/**/*.dart"
    - "lib/generated_plugin_*.dart"
    - "bin/cache/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "pubspec.yaml"

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    omit_local_variable_types: false
    unnecessary_this: false
    prefer_collection_literals: false
    always_specify_types: true
    valid_regexps: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    unnecessary_string_interpolations: true
    unnecessary_string_escapes: true
    unnecessary_parenthesis: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_null_aware_assignments: true
    unnecessary_new: true
    unnecessary_const: true
    unnecessary_brace_in_string_interps: true
    tighten_type_of_initializing_formals: false
    test_types_in_equals: true
    slash_for_doc_comments: true
    prefer_void_to_null: true
    prefer_typing_uninitialized_variables: true
    prefer_spread_collections: true
    prefer_contains: true
    prefer_adjacent_string_concatenation: true
    package_api_docs: true
    no_duplicate_case_values: true
    sort_pub_dependencies: true
    avoid_escaping_inner_quotes: true
    avoid_classes_with_only_static_members: true
    prefer_constructors_over_static_methods: true
    file_names: false
    constant_identifier_names: true
    prefer_final_locals: true
    avoid_void_async: true
    leading_newlines_in_multiline_strings: true
    await_only_futures: true
    prefer_const_constructors_in_immutables: true
    avoid_redundant_argument_values: true
    sort_child_properties_last: true
    avoid_unused_constructor_parameters: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables: true
    empty_statements: true
    sort_unnamed_constructors_first: true
    void_checks: true
    join_return_with_assignment: true
    unnecessary_await_in_return: true
    avoid_print: true
    invalid_assignment: true
    unnecessary_raw_strings: true
    avoid_positional_boolean_parameters: true
    hash_and_equals: true
    prefer_interpolation_to_compose_strings: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_function_declarations_over_variables: true
    overridden_fields: true
    camel_case_types: true
    deprecated_consistency: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true

    # exceptions
    use_build_context_synchronously: false
    non_constant_identifier_names: false
    invariant_booleans: false
    implementation_imports: false
    parameter_assignments: false
    avoid_bool_literals_in_conditional_expressions: false
    iterable_contains_unrelated_type: false
    no_adjacent_strings_in_list: false
    use_setters_to_change_properties: false
    directives_ordering: false