name: afya_moja_core
description: A shared library for `ProHealth360` and `ProHealth360 Daktari` that is responsible for rendering and exposing shared components
version: 0.3.1
homepage: https://github.com/savannahghi/afya_moja_core
repository: https://github.com/savannahghi/afya_moja_core
issue_tracker: https://github.com/savannahghi/afya_moja_core/issues
documentation: https://github.com/savannahghi/afya_moja_core/blob/main/doc/readme.md

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  app_wrapper: ^0.2.2
  cached_network_image: ^3.2.2
  chewie: ^1.3.5
  dartz: ^0.10.1
  firebase_messaging: ^14.1.0
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.2.2
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^12.0.3+1
  flutter_local_notifications_platform_interface: ^6.0.0
  flutter_svg: ^1.1.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.2.0
  google_fonts: ^2.3.3
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  just_audio: ^0.9.30
  mockito: ^5.3.2
  overlay_support: ^2.1.0
  pin_code_text_field: ^1.8.0
  plugin_platform_interface: ^2.1.3
  rxdart: ^0.27.7
  shared_themes: ^0.2.0
  sms_autofill: ^2.2.0
  stream_chat_flutter: ^5.1.0
  unicons: ^2.1.0
  video_player: ^2.4.7

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  mocktail_image_network: ^0.3.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - packages/afya_moja_core/assets/ken.png
    - packages/afya_moja_core/assets/tza.png
    - packages/afya_moja_core/assets/uga.png
    - packages/afya_moja_core/assets/usa.png
    - packages/afya_moja_core/assets/gbr.png
    - packages/afya_moja_core/assets/bel.png
    - packages/afya_moja_core/assets/nga.png
    - packages/afya_moja_core/assets/error_page_image.svg
    - packages/afya_moja_core/assets/too_many_attempts_icon.svg
    - packages/afya_moja_core/assets/save.svg
    - packages/afya_moja_core/assets/share.svg
    - packages/afya_moja_core/assets/heart.svg
    - packages/afya_moja_core/assets/placeholder_image.svg
    - packages/afya_moja_core/assets/content_image_placeholder.png
    - packages/afya_moja_core/assets/content_icon.svg
    - packages/afya_moja_core/assets/playIcon.svg
    - packages/afya_moja_core/assets/pdf_icon.svg
    - packages/afya_moja_core/assets/white_close_icon.svg
    - packages/afya_moja_core/assets/no_content_image.svg
    - packages/afya_moja_core/assets/notification_icon.svg
