name: afya_moja_core
description: A shared library for `ProHealth360` and `ProHealth360 Daktari` that is responsible for rendering and exposing shared components
version: 0.2.5
homepage: https://github.com/savannahghi/afya_moja_core
repository: https://github.com/savannahghi/afya_moja_core
issue_tracker: https://github.com/savannahghi/afya_moja_core/issues
documentation: https://github.com/savannahghi/afya_moja_core/blob/main/doc/readme.md

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  app_wrapper: ^0.1.36
  cached_network_image: ^3.2.1
  chewie: ^1.3.4
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.1.24
  flutter_html: ^3.0.0-alpha.5
  flutter_svg: ^1.1.1+1
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  google_fonts: 2.2.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.1.4
  just_audio: ^0.9.27
  mockito: ^5.0.7
  pin_code_text_field: ^1.8.0
  rxdart: ^0.27.1
  shared_themes: ^0.1.1
  sms_autofill: ^2.2.0
  unicons: ^2.0.1
  video_player: ^2.4.5

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  mocktail_image_network: ^0.3.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - packages/afya_moja_core/assets/ken.png
    - packages/afya_moja_core/assets/tza.png
    - packages/afya_moja_core/assets/uga.png
    - packages/afya_moja_core/assets/usa.png
    - packages/afya_moja_core/assets/gbr.png
    - packages/afya_moja_core/assets/bel.png
    - packages/afya_moja_core/assets/nga.png
    - packages/afya_moja_core/assets/error_page_image.svg
    - packages/afya_moja_core/assets/too_many_attempts_icon.svg
    - packages/afya_moja_core/assets/save.svg
    - packages/afya_moja_core/assets/share.svg
    - packages/afya_moja_core/assets/heart.svg
    - packages/afya_moja_core/assets/placeholder_image.svg
    - packages/afya_moja_core/assets/content_image_placeholder.png
    - packages/afya_moja_core/assets/content_icon.svg
    - packages/afya_moja_core/assets/playIcon.svg
    - packages/afya_moja_core/assets/pdf_icon.svg
    - packages/afya_moja_core/assets/white_close_icon.svg
    - packages/afya_moja_core/assets/no_content_image.svg
