name: afya_moja_core
description: A shared library for `afyamoja` and `myafyahub` that is responsible for rendering and exposing shared components
version: 0.0.9
homepage: https://github.com/savannahghi/afya_moja_core
repository: https://github.com/savannahghi/afya_moja_core
issue_tracker: https://github.com/savannahghi/afya_moja_core/issues
documentation: https://github.com/savannahghi/afya_moja_core/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_themes: ^0.1.1
  unicons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
