name: afya_moja_core
description: A shared library for `afyamoja` and `myafyahub` that is responsible for rendering and exposing shared components
version: 0.0.34
homepage: https://github.com/savannahghi/afya_moja_core
repository: https://github.com/savannahghi/afya_moja_core
issue_tracker: https://github.com/savannahghi/afya_moja_core/issues
documentation: https://github.com/savannahghi/afya_moja_core/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  google_fonts: ^2.2.0
  json_serializable: ^4.1.3
  misc_utilities: ^0.1.28-nullsafety
  pin_code_text_field: ^1.8.0
  rxdart: ^0.27.1
  shared_themes: ^0.1.1
  shared_ui_components: ^0.1.43-nullsafety
  unicons: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
