version: 2.1

jobs:
  run_tests_and_generate_coverage:
    resource_class: large
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - run:
          name: Analyze, test and report coverage
          no_output_timeout: 10m
          command: |
            flutter clean
            flutter pub get
            flutter analyze
            flutter test --coverage test/
            sudo apt-get -qq update
            sudo apt-get install -qqy lcov python3-pip
            pip3 install -Uqqq lxml && pip3 install -Uqqq beautifulsoup4
            lcov --remove coverage/lcov.info 'lib/*.g.dart' -o coverage/lcov.info
            lcov --remove coverage/lcov.info 'lib/**/*.freezed.dart' -o coverage/lcov.info
            lcov --remove coverage/lcov.info 'lib/**/*.gr.dart' -o coverage/lcov.info
            genhtml -q -o coverage coverage/lcov.info
            python3 check_coverage.py
      - store_artifacts:
          path: coverage/

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests_and_generate_coverage
